[rule]
description = """
Identifies attempts to perform a network connection from a suspicious unbacked memory block. This may be the result of
code injection.
"""
id = "720e0265-03bc-4cb7-9116-7fad5ea9cdfc"
license = "Elastic License v2"
name = "Network Connect API from Unbacked Memory"
os_list = ["windows"]
version = "1.0.8"

query = '''
api where process.Ext.api.name == "connect" and process.Ext.api.summary: "*ipv4*" and

 process.thread.Ext.call_stack_final_user_module.name == "Unbacked" and
 (
  process.thread.Ext.call_stack_summary :
               ("ntdll.dll|mswsock.dll|ws2_32.dll|Unbacked",
                "ntdll.dll|mswsock.dll|Unbacked",
                "wow64cpu.dll|wow64.dll|ntdll.dll|mswsock.dll|ws2_32.dll|Unbacked",
                "wow64cpu.dll|wow64.dll|ntdll.dll|mswsock.dll|Unbacked") or

  ((process.code_signature.trusted == false or process.code_signature.exists == false) and
   startswith~(process.thread.Ext.call_stack_summary, concat("wow64cpu.dll|wow64.dll|ntdll.dll|mswsock.dll|ws2_32.dll|Unbacked|", process.name))) or

   ((process.code_signature.trusted == false or process.code_signature.exists == false) and
    startswith~(process.thread.Ext.call_stack_summary, concat("ntdll.dll|mswsock.dll|ws2_32.dll|Unbacked", process.name)))
 ) and

 /* trailing bytes are not null */
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : "Unbacked*" and $entry.callsite_trailing_bytes : "?*") and

 /* excluding signed final usermod */
 not _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry, $entry.trusted == true) and

 not process.thread.Ext.call_stack_final_user_module.hash.sha256 :
                                  ("02ecce804add1da0a9e7be506f7369d3d5753c51c80abe32b24be05c321c5ff7",
                                   "f823fc285b259fd0a5391a5c807279e90fe5317e6cfd7b00a49f07c278832cbc", 
                                   "236b9ab2b531da7312da1429cba1bd9f45cae4ed46cba1792924013b9919f8cf", 
                                   "5d4708e841bdd2523c963e45932555ba98e203c6a99f242573f251374f73cb63", 
                                   "ff4dd86a9ef8ccedd9a01dee516775eea75edcef0ff313b718df3dc4a026f395",
                                   "0e675101b1814b932f8c1209b5e355636c18767da413a261667ce2bedd3c7914",
                                   "aeda6c3b3b1dc1e91d1cbbea6863eaf5fe02eef74827fe533f4b7d55e388a9b1",
                                   "99f9058c1481370d03a511a8863a9b6e36c34d4f0066b17ad0f6666c86eed152",
                                   "9b1865415f947505eff3084830193d1a6bf317d8e704d401b1a8ffb91a3d9277",
                                   "7f28d5f5d96183ed01c345fdc5d28e82ae255aa19ecb329ab9fa9ecdf10f79de",
                                   "5ec183e4e31a18a7788ffa4514e1e555d458725e4521160221ea36df5e29a35f",
                                   "5d1ace7a28fb13f34a4f56045f41285b2f07764f42e09fc4d5ce72b10ffbed38",
                                   "df13445949901d9f43575ad8fd5005a490e9a2fa68e27e26e6ea6d4014b83635",
                                   "8b354c30a6fccb12963cf2bf06fcf60efcc2bef7e3b735cab36f4b26e8cd105b",
                                   "c809da8be3cad745801f3668df829bddc39e7ffb0c526fe98ada697b60811922",
                                   "b4e067d5b1f09821e7a3b6106547ee23572f64e604ffa29041b8cbc7e63b58a7",
                                   "dcfa8e77235026558f65e6ab82d2b9e69768f023204062f628234b2b5506fd32",
                                   "617b0977d387472a4ca0948f1ba19640a21d1fa1dca52e3047c5e630af231062",
                                   "50f903bc4b496b94051b9cba15eccd9c25bb963c7424f2845fbc0897bd7d391d",
                                   "c094179af7a6a3bfae751fc30ff13b711e055ffa563fc98b3d3b3aa57584a424",
                                   "2fe43a4716927f4600f44bfc7ffa43584fb5bea404ff5624d4bb5efaddec174a",
                                   "bb55748883f650e45921b875a546e0174ff8251d77043d3cab4de60eff7cd9f8",
                                   "f2c8fbd754527f3411c31068975f316970fcb3bb7ba611d5d2f20d17489e6d32",
                                   "c160ce8529cd5131f1c349bc92c5b3e989b0cac7fcbdd1318eb484eb3b4ca49f",
                                   "3d86479ab47b249241e7d392ef5daf2263b341f4a77755ac285c629dfc71f06c",
                                   "bf85b58dada12a821a8ee445a6d7b97b7e984eb4db88a9bcb3e3fa698c88d345") and

 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : "Unbacked*" and
                  $entry.callsite_trailing_bytes :
                       ("*85f60f95c10fb6c9894dac488bcce82f000000908b45*",
                        "*8bc641c6470c01488b558849895710488d65c85b5e5f415c41",
                        "488b9550ffffffc6420c01833d3efbd15f007406ff150a18d15f89855cffffffe8a7f4535f908b8d5cffffff898d70ffffff83bd70ffffff000f95c10fb6c989")) and

 not process.thread.Ext.call_stack_final_user_module.protection_provenance like ("Unknown", "Kernel", "Kernel|*", "*.ni.dll", "coreclr.dll", "Undetermined", "hmpalert.dll", "em003_64.dll") and

 not process.executable == "C:\\Program Files\\Veeam\\Backup and Replication\\Backup\\Veeam.Backup.Service.exe" and
 not process.thread.Ext.call_stack_final_user_module.protection_provenance == "inprocessclient64.dll"
'''

min_endpoint_version = "8.14.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[threat]]
framework = "MITRE ATT&CK"

[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.14.0"
