[rule]
description = "Identifies suspicious writes to the memory space of a remote process. this may indicate a code injection attempt."
id = "33270c59-e034-4e5b-accb-b6a23681a0d3"
license = "Elastic License v2"
name = "Suspicious Memory Write to a Remote Process"
os_list = ["windows"]
reference = [
    "https://www.elastic.co/security-labs/doubling-down-etw-callstacks",
    "https://www.elastic.co/security-labs/pikabot-i-choose-you",
]
version = "1.0.21"

query = '''
api where process.Ext.api.name == "WriteProcessMemory" and process.executable : "?:\\*" and
 process.Ext.api.behaviors == "cross-process" and process.Ext.api.parameters.size >= 10000 and
 not process.executable :
             ("?:\\Program Files\\*.exe",
              "?:\\Program Files (x86)\\*.exe",
              "?:\\Windows\\System32\\lsass.exe",
              "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*.exe",
              "?:\\Windows\\SysWOW64\\inetsrv\\w3wp.exe") and
 not _arraysearch(process.thread.Ext.call_stack, $entry, 
                  $entry.symbol_info : ("*msys-*.dll!_feinitialise*", "*cygwin*.dll!setprogname+*", 
                                        "?:\\program files*\\cylance\\desktop\\cylancememdef*.dll!*")) and
 not (stringcontains~(process.Ext.api.summary, process.name) and not process.executable : "?:\\Windows\\*") and
 not (process.code_signature.trusted == true and 
      process.code_signature.subject_name : 
              ("GEOVISION INC.", "COMPUTACION EN ACCION SA DE CV", "Crownalytics, LLC", "Johannes Schindelin", 
               "INCA Internet Co.,Ltd.", "Mark Straver", "Micro Systemation AB (publ)", "HardestCodesEst OU", 
               "MUSARUBRA US LLC", "Tropic Management Systems Inc.", "GIE Sesam Vitale", "Rocket Software, Inc.",
               "Mesalvo Mannheim GmbH", "Devolutions Inc", "IRONMACE Co., Ltd.", "Calyx Technology, Inc.")) and
 not (process.executable : "?:\\Users\\*\\AppData\\Local\\Mozilla Firefox\\firefox.exe" and 
      process.code_signature.subject_name : "Mozilla Corporation" and process.code_signature.trusted == true) and 
 not (process.name : "rundll32.exe" and process.parent.executable : "?:\\Users\\*\\AppData\\Local\\Temp\\SNXAC\\STAProxy.exe" and
        process.command_line : "*\\Users\\*\\AppData\\Local\\Temp\\snxac\\*\\sta.dll*") and 
 not (process.executable : "?:\\Windows\\System32\\Windows.WARP.JITService.exe" and 
      process.parent.executable : "?:\\Windows\\System32\\svchost.exe" and user.id : "S-1-5-19") and 
 not (process.executable : "?:\\Windows\\System32\\winrdlv3.exe" and 
      process.code_signature.subject_name : "T.E.C Solutions (G.Z.)Limited" and process.code_signature.trusted == true) and 
 not (process.executable : ("C:\\724Access\\cygwin\\bin\\bash.exe", "C:\\724Access\\cygwin\\usr\\sbin\\sshd.exe") and 
      process.Ext.api.summary : "WriteProcessMemory( Unknown, Data, * )") and 
 not (process.executable : "?:\\Windows\\System32\\Windows.WARP.JITService.exe" and 
      process.Ext.api.summary : "WriteProcessMemory( microsoftpdfreader.exe, Data, 0x3000 )") and 
 not (process.parent.executable : "?:\\Program Files (x86)\\Quicken\\qw.exe" and process.Ext.api.summary : "*rundll32.exe*") and 
 not (process.parent.executable : "?:\\Program Files (x86)\\JTECH Medical\\Northstar\\Northstar.exe" and 
      process.Ext.api.summary : "WriteProcessMemory( northstar.exe, casper.dll, * )") and 
 not (process.executable : "?:\\Windows\\SysWOW64\\mavinject.exe" and
      process.parent.executable : "?:\\Windows\\System32\\AppVClient.exe") and 
 not process.parent.executable : ("?:\\Program Files (x86)\\Embarcadero\\Studio\\*\\bin\\bds.exe", "?:\\Program Files\\Embarcadero\\Studio\\*\\bin\\bds.exe") and 
 not user.id : ("S-1-5-20", "S-1-5-19") and 
 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.callsite_trailing_bytes : "85c0750*") and
 not (process.parent.executable : "C:\\Program Files (x86)\\StarMoney ?? Basic S-Edition\\app\\StarMoney.exe" and
      process.command_line : "\"C:\\WINDOWS\\system32\\rundll32.exe\" \"C:\\Program Files (x86)\\StarMoney ?? Basic S-Edition\\app\\sfmcoresd4164.dll\",#25") and
 not (process.name : "powershell.exe" and
      process.Ext.api.summary : ("WriteProcessMemory( aspnet_compiler.exe, Unbacked, 0xa800 )",
                                 "WriteProcessMemory( searchindexer.exe, Data, 0x41800 )",
                                 "WriteProcessMemory( bash.exe, Data, 0x40d0 )",
                                 "WriteProcessMemory( searchindexer.exe, Unbacked, 0x41800 )")) and
 not (process.name : "rundll32.exe" and process.Ext.api.summary : "*rundll32.exe*" and
      process.command_line : "\"?:\\Windows\\system32\\rundll32.exe\"  --enable-speech-input --lang=* --enable-media-stream --no-sandbox") and
 not (process.executable : "?:\\Windows\\SysWOW64\\mavinject.exe" and
      process.parent.executable : "?:\\Windows\\System32\\AppVClient.exe" and process.Ext.api.summary : "*VRManagement*") and
 not (process.executable : "C:\\Windows\\SysWOW64\\rundll32.exe" and
      process.command_line : "rundll32.exe \"C:\\ProgramData\\FastTrack Software\\Admin By Request\\ShellHelper32.dll\",#1") and
 not process.thread.Ext.call_stack_summary :
                        ("ntdll.dll|kernelbase.dll|shell.dll|windows.storage.dll|shell32.dll|windows.storage.dll|shell32.dll|startallbackx64.dll|shcore.dll|kernel32.dll|ntdll.dll",
                         "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|Unknown|kernel32.dll|ntdll.dll",
                         "ntdll.dll|kernelbase.dll|shell.dll|windows.storage.dll|shell32.dll|windows.storage.dll|shell32.dll|shell.dll|taskbar.dll|shcore.dll|kernel32.dll|ntdll.dll",
                         "ntdll.dll|kernelbase.dll|sta.dll|kernel32.dll|ntdll.dll",
                         "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|ebehmoni.dll|Unbacked|kernel32.dll|ntdll.dll",
                         "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|Unknown|mscorlib.ni.dll|clr.dll|kernel32.dll|ntdll.dll",
                         "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|ebehmoni.dll|Unknown|kernel32.dll|ntdll.dll") and
 not process.thread.Ext.call_stack_final_user_module.hash.sha256 in
                                               ("ec363d03afa97033dc91cbf7c9a491fc693189f7a0a19bffc631bcb7dc715b47",
                                                "2fec0c389dd0932c59eee19ca24c720b6521603e5ead78e3e070aa561b73be32",
                                                "f7c78dba07128af325d8da99138ebf78be163ecfb5da5b01fa6b65b96efecef1",
                                                "a06e08a8ed7af0535c63c5a41aa5dfd8aece653c9ea539308e3e23644cd61b3d",
                                                "b4f289b5bf0beb59e7ba8d00b45ffaa582114c22a959bb8912cd8b903748f91b") and
 not _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry, $entry.trusted == true and
                  $entry.subject_name in ("Microsoft Windows Hardware Compatibility Publisher",
                                          "Microsoft Windows Software Compatibility Publisher",
                                          "FastTrack Software ApS",  "FastTrack Software Aps", "Promon AS", "PC Matic, Inc"))
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0
tree = true

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
