[rule]
description = """
Identifies the call of Memory Windows APIs indirectly via a proxy function using ROP gadgets. This may be the result of
an evasion attempt to hide the origin of the API call from the call stack such as unbacked memory region.
"""
id = "2189bb9a-e711-43d1-9f7d-ba8e12c788da"
license = "Elastic License v2"
name = "Potential API Call Stack Spoofing"
os_list = ["windows"]
reference = ["https://github.com/klezVirus/SilentMoonwalk"]
version = "1.0.5"

query = '''
api where process.Ext.api.behaviors == "proxy_call" and process.Ext.api.behaviors == "image_rop" and
 process.executable != null and
  process.Ext.api.metadata.target_address_name : ("Unbacked", "ntdll.dll", "kernelbase.dll", "kernel32.dll", "*.exe") and
  process.Ext.api.name in ("VirtualAlloc", "VirtualProtect", "VirtualAllocEx", "VirtualProtectEx", "WriteProcessMemory", "MapViewOfFile", "MapViewOfFile2", "SetThreadContext", "SuspendThread") and
  process.thread.Ext.call_stack_final_user_module.name == "Undetermined" and
  /* uncomment once added to schema
  process.thread.Ext.call_stack_final_user_module.reason != "Empty" and
  */
  process.thread.Ext.call_stack_summary like "ntdll.dll|*" and not process.thread.Ext.call_stack_summary like ("*Unbacked*", "*Unknown*") and
  not process.thread.Ext.call_stack_summary like
                                ("ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|*",
                                 "ntdll.dll|imagehlp.dll",
                                 "ntdll.dll|kernelbase.dll|imagehlp.dll",
                                 "ntdll.dll|verifier.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|*",
                                 "ntdll.dll|verifier.dll|cylancememdef64.dll|ntdll.dll|verifier.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll",
                                 "ntdll.dll|kernelbase.dll|verifier.dll|jitv.dll|verifier.dll|ntdll.dll|kernelbase.dll|interceptor.dll|combase.dll|searchprotocolhost.exe|kernel32.dll|ntdll.dll") and
  not (process.executable : ("C:\\Windows\\System32\\wbem\\WmiPrvSE.exe", "C:\\Windows\\System32\\audiodg.exe", "C:\\Windows\\System32\\drvinst.exe") and
       process.parent.executable : "C:\\Windows\\System32\\svchost.exe" and user.id in ("S-1-5-18", "S-1-5-19", "S-1-5-20")) and
  not (process.executable : "C:\\Windows\\System32\\svchost.exe" and user.id == "S-1-5-19" and
       process.parent.executable : "C:\\Windows\\System32\\services.exe")
'''

min_endpoint_version = "8.14.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"

[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.14.0"
