[rule]
description = """
Identifies the execution of a script utility followed by calling Windows memory manipulation API with suspicious
arguments. This may indicate an attempt to perform code injection from a malicious script.
"""
id = "fdd3d1e9-e7d2-4226-9e7c-0f8e77acac6d"
license = "Elastic License v2"
name = "Suspicious API Call from a Script Interpreter"
os_list = ["windows"]
reference = ["https://www.elastic.co/security-labs/doubling-down-etw-callstacks"]
version = "1.0.12"

query = '''
sequence by process.entity_id with maxspan=5m
 [process where event.action == "start" and 
  not user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and 
  (
   process.pe.original_file_name : ("AutoHotkey.exe", "KIX32.EXE", "cscript.exe", "wscript.exe", "mshta.exe", "matlab.exe") or
   process.name : ("AutoHotkey*.exe", "rebol-view*.exe", "AutoIt*.exe", "cscript.exe", "wscript.exe", "mshta.exe", "matlab.exe") or
   process.code_signature.subject_name : ("The MathWorks, Inc.", "AutoIt Consulting Ltd") or
   process.hash.sha256 : "215e28f9660472b6271a9902573c9d190e4d7ccca33fcf8d6054941d52a3ab85" or 
   process.executable :
                ("?:\\Program Files\\Java\\jre*\\bin\\java.exe",
                 "?:\\Program Files (x86)\\Java\\jre*\\bin\\java.exe",
                 "?:\\Program Files\\AdoptOpenJDK\\jdk-*\\bin\\java.exe",
                 "?:\\Program Files (x86)\\AdoptOpenJDK\\jdk-*\\bin\\java.exe")
  ) and 
  not (process.name : ("cscript.exe", "wscript.exe") and
       process.args : ("?:\\Program Files (x86)\\*", "?:\\Program Files\\*",  "\\\\*\\NETLOGON\\*", "\\\\*\\SysVol\\*")) and

  not process.executable == "C:\\Program Files\\MuleSoft\\RPABuilder\\NgCore\\bin\\3rdParty\\AutoIt3.exe"
  ]
 [api where
  process.Ext.api.behaviors : ("shellcode", "allocate_shellcode", "execute_shellcode", "unbacked_rwx", "image_rwx") and
  not process.Ext.api.name : ("VirtualProtect", "NtQueueApcThread", "SetWindowsHookEx") and 
  not process.thread.Ext.call_stack_summary : ("Unknown", "Unbacked", "Undetermined") and
  not process.Ext.api.summary : "VirtualProtect*msvcr*.dll,*" and
  not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : ("Kernel|*", "kernel", "epmpthe.dll")) and 
  not process.thread.Ext.call_stack_final_user_module.protection_provenance : ("Kernel", "Kernel|*") and
  not process.thread.Ext.call_stack_final_user_module.name : ("Unknown", "Undetermined") and
  not (process.Ext.api.behaviors == "image_rwx" and process.thread.Ext.call_stack_final_user_module.name : "mscorwks.dll") and
  not process.thread.Ext.call_stack_final_user_module.path :
                               ("?:\\Program Files\\*.dll",
                                "?:\\Program Files (x86)\\*.dll",
                                "?:\\Windows\\System32\\*.dll",
                                "?:\\Windows\\SysWOW64\\*.dll",
                                "\\Program Files\\*.dll",
                                "\\Program Files (x86)\\*.dll",
                                "\\Windows\\System32\\*.dll",
                                "\\Windows\\SysWOW64\\*.dll",
                                "*\\Windows\\apppatch\\AppPatch64\\exploitblocker.dll",
                                "*\\Windows\\FireEye\\AppMonitorDll.dll") and
  process.thread.Ext.call_stack_final_user_module.hash.sha256 != "8851b734602eb00da5b1cfc1e40d38f1cb32e0add2df257ff9d7dbd520b4d5da"]
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
