[rule]
description = """
Detects Windows Memory API calls from a null terminated thread call stack. This could be the result of an attempt to
conceal the true source of the call.
"""
id = "a4684714-f605-4944-98de-e593246faf15"
license = "Elastic License v2"
name = "Suspicious Null Terminated Call Stack"
os_list = ["windows"]
reference = ["https://www.elastic.co/security-labs/doubling-down-etw-callstacks"]
version = "1.0.7"

query = '''
api where
   process.Ext.api.name : "VirtualProtect" and process.Ext.token.integrity_level_name != "low" and
   process.thread.Ext.call_stack_summary in ("ntdll.dll|Unbacked", "ntdll.dll|kernelbase.dll|Unbacked") and
   process.thread.Ext.call_stack_final_user_module.name : "Unbacked" and
   (
    process.thread.Ext.call_stack_final_user_module.protection_provenance : "Unbacked" or

    ((process.code_signature.trusted == false or process.code_signature.exists == false) and
      stringcontains~(process.thread.Ext.call_stack_final_user_module.protection_provenance, process.name)) or

    _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry, $entry.subject_name in ("Microsoft Windows", "Microsoft Corporation"))
    ) and 
_arraysearch(process.thread.Ext.call_stack, $entry, 
             $entry.callsite_trailing_bytes : "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000") and 
_arraysearch(process.thread.Ext.call_stack, $entry, 
             $entry.callsite_leading_bytes : "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000") and
/* Steam */
not process.thread.Ext.call_stack_final_user_module.hash.sha256 in
              ("c434208894f07f604b852f29b8edc3a58c4de63de783373733e72b2b73f33be9",
               "5438c19007ad96da0a969c0c0caaf00aa06375f1a6e85073f91a1392af94d059",
               "2f3b9ba5b769c89297c10c77f50223e9e88737dd3fe56e8c00adeeaa198480f9",
               "fdf036edcd2fc6997a6eeaac4b58e4b533cd6abdf15d18a53621832bff038be0",
               "93f53280052d0f700259b42a62f8658d9b2a741b54063f277e9b83264448fb21",
               "0696e0617a028101d85db50a4f109fac15be3e1ebe122b94f805763d8008ddfc",
               "115d7fdc184219a5cfe13a82d1d193d8dca5e5ccdeaaeed41c157754593aa2c1",
               "68e6c21a97c2a0824ff75961a771605dacbd73f17e33e8e7265741535a3818c3")
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"

[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
