[rule]
description = """
Identifies interactive logon attempt with alternate credentials and by an unusual process. Adversaries may create a new
token to escalate privileges and bypass access controls.
"""
id = "1ee7b771-28d6-4bf5-a227-d1c8bf04df96"
license = "Elastic License v2"
name = "Interactive Logon by a Suspicious Process"
os_list = ["windows"]
reference = ["https://attack.mitre.org/techniques/T1134/002/"]
version = "1.0.4"

query = '''
authentication where event.action == "log_on" and event.code == "4624" and
 process.Ext.session_info.logon_type == "Interactive" and process.executable : "C:\\*" and
 user.id like ("S-1-5-21*", "S-1-12-*") and (user.effective.id != null and user.effective.id like ("S-1-5-21*", "S-1-12-*")) and
 not (process.code_signature.trusted == true and
      process.code_signature.subject_name in
           ("TeamViewer", "TeamViewer GmbH", "TeamViewer Germany GmbH", "LogMeIn, Inc.", "Siemens AG",
            "QlikTech International AB", "Bomgar Corporation", "NinjaOne LLC", "Island Technology Inc.", "CA, Inc.",
            "CAS Software AG", "Imprivata, Inc.", "Google LLC", "NoMachine S.a.r.l.", "Imprivata, Inc", "Laserfiche",
            "COC COC COMPANY LIMITED", "Given Imaging Ltd", "Luis Cobian Dorta", "Brave Software, Inc.", "CyberArk Software Ltd.",
            "Kofax, Inc.", "Education Management Solutions LLC", "Seagull Scientific, Inc", "Ivanti, Inc.", "Opera Norway AS",
            "PDQ.com Corporation", "itelio GmbH", "Mozilla Corporation", "Vivaldi Technologies AS", "GoTo Technologies USA, LLC",
            "Devolutions Inc", "Seagull Scientific Inc.", "Senior Sistemas S/A", "Rsupport Co., Ltd.")) and
 not process.executable :
            ("C:\\Windows\\System32\\winlogon.exe",
             "C:\\Windows\\System32\\wininit.exe",
             "C:\\Windows\\System32\\lsass.exe",
             "C:\\Windows\\explorer.exe",
             "C:\\Windows\\System32\\ServerManager.exe",
             "C:\\Windows\\System32\\svchost.exe",
             "C:\\Windows\\System32\\wsmprovhost.exe",
             "C:\\Windows\\System32\\CredentialEnrollmentManager.exe",
             "C:\\Program Files\\Okta\\Okta Verify\\OktaVerify.exe",
             "C:\\Windows\\System32\\CredentialUIBroker.exe",
             "C:\\Program Files (x86)\\Okta\\Okta Verify\\OktaVerify.exe",
             "C:\\Program Files\\Island\\Island\\Application\\Island.exe",
             "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
             "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
             "C:\\Program Files\\Microsoft\\Kerberos Configuration Manager for SQL Server\\KerberosConfigMgr.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\cpms..tion_*\\CPMSPROD.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\merg...app_*\\Client.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\micr..tion_*\\Microsoft.Online.CSE.Hybrid.App.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\chec..tion_*\\CheckWriter.exe",
             "C:\\Users\\*\\AppData\\Local\\Apps\\2.0\\*\\rscc..tion_*\\RSC Count.exe",
             "C:\\Program Files\\Microsoft SQL Server\\*\\ReportingServicesService.exe",
             "C:\\Program Files\\Microsoft SQL Server Reporting Services\\SSRS\\Portal\\RSPortal.exe",
             "C:\\Program Files (x86)\\HCL\\AppScan Enterprise\\AgentHost.exe",
             "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
             "C:\\Windows\\System32\\oobe\\UserOOBEBroker.exe",
             "C:\\Windows\\SysWOW64\\inetsrv\\w3wp.exe",
             "C:\\Windows\\System32\\inetsrv\\w3wp.exe",
             "C:\\Windows\\SysWOW64\\msiexec.exe",
             "C:\\Windows\\System32\\msiexec.exe",
             "C:\\Program Files (x86)\\Icon Global\\carelink+\\CareLinkPlus.exe",
             "C:\\Program Files (x86)\\Cobian Backup ??\\Cobian.exe",
             "C:\\Windows\\ImmersiveControlPanel\\SystemSettings.exe",
             "C:\\Program Files\\Microsoft SQL Server\\*\\Shared\\sqlsqm.exe",
             "C:\\Program Files (x86)\\ResMed\\ResScan?\\ResScan.exe",
             "C:\\Windows\\System32\\CredentialUIBroker.exe",
             "C:\\Windows\\System32\\UserAccountBroker.exe",
             "C:\\Windows\\System32\\mmc.exe",
             "C:\\Program Files (x86)\\KIC H\\KIC.exe",
             "C:\\Windows\\System32\\CloudExperienceHostBroker.exe",
             "C:\\Windows\\System32\\Autologon64.exe",
             "C:\\Program Files (x86)\\Microsoft Visual Studio\\20??\\Enterprise\\Common?\\IDE\\CommonExtensions\\Microsoft\\SSAS\\LocalServer\\msmdsrv.exe",
             "C:\\Program Files (x86)\\AMG Resources\\SDDT\\*\\Support Desk Domain Tools.exe",
             "C:\\Program Files\\Microsoft SQL Server Reporting Services\\*\\ReportingServicesService.exe",
             "C:\\Program Files (x86)\\Merge Healthcare\\Client\\Client.exe",
             "C:\\Program Files\\RunAsTool\\RunAsTool.exe")
'''

min_endpoint_version = "8.15.1"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1134"
name = "Access Token Manipulation"
reference = "https://attack.mitre.org/techniques/T1134/"
[[threat.technique.subtechnique]]
id = "T1134.001"
name = "Token Impersonation/Theft"
reference = "https://attack.mitre.org/techniques/T1134/001/"

[[threat.technique.subtechnique]]
id = "T1134.002"
name = "Create Process with Token"
reference = "https://attack.mitre.org/techniques/T1134/002/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "8.15.1"
