[rule]
description = """
Detects when a discovery command is executed followed by the immediate modification of a suspicious file via the same
process. Many different types of malware will execute discovery commands, save their output to a file and then
exfiltrate that file via their C2 channel.
"""
id = "10076d7d-9ee0-44b7-99c7-9ed24c7ccf1b"
license = "Elastic License v2"
name = "Discovery command output written to a suspicious file"
os_list = ["macos"]
version = "1.0.3"

query = '''
sequence by process.entity_id with maxspan=5s
[process where event.type == "start" and event.action == "exec" and process.parent.name : ("bash", "sh", "zsh") and 
  process.name in ("whoami", "ifconfig", "system_profiler", "dscl", "arch", "csrutil") and process.args_count == 1] as event0
[file where event.action == "modification" and file.path : ("/Users/Shared/*", "/tmp/*", "/private/tmp/*", "/var/tmp/*", "/*/.*") and 
  not file.Ext.header_bytes : "*" and stringcontains~(event0.process.command_line, file.name)]
'''

min_endpoint_version = "8.11.1"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1074"
name = "Data Staged"
reference = "https://attack.mitre.org/techniques/T1074/"
[[threat.technique.subtechnique]]
id = "T1074.001"
name = "Local Data Staging"
reference = "https://attack.mitre.org/techniques/T1074/001/"



[threat.tactic]
id = "TA0009"
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"

[internal]
min_endpoint_version = "8.11.1"
