[rule]
description = """
Detects when a new payload is dropped into a temp location and executed with OsaScript as a background process. The
Apfell agent payload utilizes this method in order to drop a new payload to disk and then execute it in order to
generate a new callback.
"""
id = "2cf4a0ba-6d6e-4984-963e-ee4785f8c9b6"
license = "Elastic License v2"
name = "Osascript Payload Drop and Execute"
os_list = ["macos"]
reference = [
    "https://github.com/MythicAgents/apfell/",
    "https://github.com/MythicAgents/apfell/blob/master/documentation-payload/apfell/commands/spawn_drop_and_execute.md",
    "https://www.elastic.co/security-labs/beyond-the-wail",
]
version = "1.0.10"

query = '''
sequence with maxspan=10s
[file where event.action == "modification" and 
  file.path like ("/tmp/*", "/private/tmp/*", "/var/tmp/*", "/private/var/tmp/*")] by process.entity_id
[process where event.type == "start" and event.action == "exec" and 
  process.name == "osascript" and process.args like ("/tmp/*", "/private/tmp/*", "/var/tmp/*", "/private/var/tmp/*")] by process.parent.entity_id
'''

min_endpoint_version = "8.11.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.11.0"
