[rule]
description = """
Identifies when a process running in a suspicious directory, such as the temp directory attempts to download a second
stage payload. This behavior is consistent with malware families such as Bundlore.
"""
id = "04d124d4-2be7-405e-b830-9494f927a51e"
license = "Elastic License v2"
name = "Payload Downloaded by Process Running in Suspicious Directory"
os_list = ["macos"]
reference = ["https://attack.mitre.org/software/S0482/", "https://objective-see.com/blog/blog_0x69.html"]
version = "1.0.35"

query = '''
sequence by process.entity_id with maxspan=30s
  [process where event.action == "exec" and 
   process.name in ("curl", "nscurl") and process.args : "http*://*/*" and
    descendant of [
      process where event.action == "exec" and
        process.executable : (
          "/tmp/*",
          "/Users/*/Library/Preferences/*",
          "/Users/*/Library/Services/*",
          "/var/tmp/*",
          "/var/folders/*",
          "/var/lib/*",
          "/Users/Shared/*",
          "/Library/Graphics/*",
          "/Library/Containers/*", 
          "/Users/*/Library/Containers/*", 
          "/var/root/*", 
          "/Library/WebServer/*", 
          "/Library/Fonts/*") 
  ] and not 
  process.args : ("https://omahaproxy.appspot.com/history", 
                  "https://console.jumpcloud.com/api/systems/*", 
                  "/usr/local/Homebrew/*",
                  "/opt/jc//jumpcloud-agent.pkg",
                  "Homebrew/*",
                  "*/opt/homebrew/*",
                  "http*://*.jamfcloud.com/*",
                  "http*elastic.co*",
                  "http*localhost*",
                  "http*127.0.0.1*",
                  "http*0.0.0.0*",
                  "*jumpcloud.osquery_manager*",
                  "https://zoom.us/client/*") and 
  not process.parent.executable : ("/usr/local/munki/*",
                                   "/System/*",
                                   "/opt/homebrew/*",
                                   "/Library/Management/*") and
  not process.Ext.effective_parent.executable like ("/Library/Application Support/JAMF/Jamf.app/Contents/MacOS/JamfDaemon.app/Contents/MacOS/JamfDaemon",
                                                    "/opt/jc/bin/jumpcloud-agent")
  ]
  [network where event.action == "connection_attempted" and process.name in~ ("curl", "nscurl") and
   not cidrmatch(destination.ip, "10.0.0.0/8", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24",
       "192.0.0.0/29", "192.0.0.8/32", "192.0.0.9/32", "192.0.0.10/32", "192.0.0.170/32", "192.0.0.171/32",
       "192.0.2.0/24", "192.31.196.0/24", "192.52.193.0/24", "192.168.0.0/16", "192.88.99.0/24", "224.0.0.0/4",
       "100.64.0.0/10", "192.175.48.0/24","198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24", "240.0.0.0/4", "::1",
       "FE80::/10", "FF00::/8")]
'''

min_endpoint_version = "8.11.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1105"
name = "Ingress Tool Transfer"
reference = "https://attack.mitre.org/techniques/T1105/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.11.0"
