[rule]
description = """
Detects the clearing of file attributes via the Xattr binary, to include the quarantine attribute, of a file in the
users home directory by a shell interpreter ultimately spawned via the Terminal application. This specific invocation of
Xattr is unusual and has been observed by various macOS stealer samples to clear the quarantine attribute of their
payload and folders.
"""
id = "e12fa85d-e173-402f-b43e-5bbc6210cdd5"
license = "Elastic License v2"
name = "Suspicious File Attribute Clearing"
os_list = ["macos"]
version = "1.0.4"

query = '''
process where event.type == "start" and event.action == "exec" and process.name : "xattr" and (
 (process.args in ("-rc", "-cr")) or (process.args == "-r" and process.args == "-c") or (process.args == "-c")) and 
 process.parent.name in~ ("bash", "sh", "zsh", "osascript") and 
 process.Ext.effective_parent.executable == "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal"
'''

min_endpoint_version = "8.11.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1553"
name = "Subvert Trust Controls"
reference = "https://attack.mitre.org/techniques/T1553/"
[[threat.technique.subtechnique]]
id = "T1553.001"
name = "Gatekeeper Bypass"
reference = "https://attack.mitre.org/techniques/T1553/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.11.0"
