[rule]
description = """
Identifies when the openssl utility is used to decode and/or decrypt a payload and write it to an abnormal or suspicious
directory. Malware authors may attempt to evade detection by encoding and/or encrypting their payload.
"""
id = "a0fce633-b6ee-4e4c-b6c7-ba46b8561e9e"
license = "Elastic License v2"
name = "Linux Decoded or Decrypted Payload Written to Suspicious Directory"
os_list = ["linux"]
reference = ["https://attack.mitre.org/software/S0482/"]
version = "1.0.5"

query = '''
process where event.action == "exec" and event.type == "start" and (
  (process.name == "openssl" and process.args : "-out" and process.args : "enc" and process.args : ("-d", "-base64") and
   process.args : ("/var/tmp/*", "/dev/shm*", "/var/www/*")) or 
  (process.name == "base64" and process.args : "-d" and
   process.args : ("/var/tmp/*", "/dev/shm*", "/var/www/*"))
) and not process.parent.args : "*/var/lib/waagent/*" and not process.parent.name == "platform-python"
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"


[[threat.technique]]
id = "T1204"
name = "User Execution"
reference = "https://attack.mitre.org/techniques/T1204/"
[[threat.technique.subtechnique]]
id = "T1204.002"
name = "Malicious File"
reference = "https://attack.mitre.org/techniques/T1204/002/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1027"
name = "Obfuscated Files or Information"
reference = "https://attack.mitre.org/techniques/T1027/"

[[threat.technique]]
id = "T1140"
name = "Deobfuscate/Decode Files or Information"
reference = "https://attack.mitre.org/techniques/T1140/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
