[rule]
description = """
This rule detects the execution of the socat command with suspicious arguments. Attackers may use socat to set up a
listener or establish a reverse connection.
"""
id = "613da93c-226e-4150-9125-3b476103c0b9"
license = "Elastic License v2"
name = "Socat Reverse Shell or Listener Activity"
os_list = ["linux"]
version = "1.0.5"

query = '''
process where event.type == "start" and event.action == "exec" and process.name == "socat" and
process.args like ("*exec*", "*tty*") and process.args like ("*tcp*", "*udp*", "*openssl*", "*file*") and
not (
  process.args like ("*127.0.0.1*", "*localhost*", "*/dev/tty*") or
  process.parent.executable == "/usr/bin/wsrep_sst_xtrabackup-v2"
)
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.parent.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "7.15.0"
