[rule]
description = """
This rule detects the creation of unusually labeled named pipes (FIFOs) by the mkfifo command, which is often used by
attackers to establish persistence on a target system or to execute commands in the background.
"""
id = "2f4275f8-b305-455d-9f1f-c67574cc6b38"
license = "Elastic License v2"
name = "Suspicious Named Pipe Creation"
os_list = ["linux"]
version = "1.0.6"

query = '''
process where event.type == "start" and event.action == "exec" and process.name == "mkfifo" and 
process.parent.name in ("bash", "dash", "sh", "tcsh", "csh", "zsh", "ksh", "fish") and
process.args like ("/tmp/*", "/var/tmp/*", "/dev/shm/*") and not (

  // In Linux, when processes create named pipes, these are often by default labeled or identified with "fifo" in the name.

  process.args like (
    "/*fifo*", "/tmp/gitstatus.*", "/tmp/tmp.*", "/var/log/elog/scan_download//SCAN/*", "/tmp/tracee/pipe", "/source/*",
    "/tmp/phpstderr", "/var/run/*", "/tmp/pg_cluster@15-main", "/tmp/pg_cluster@15-audit", "/tmp/amazon-kinesis-*",
    "/tmp/scalr-agent/*", "/tmp/com_pipe", "/tmp/agent_linux_x86_64.sh.pipe.*", "/tmp/protopipe-*", "/var/tmp/dracut*",
    "--version", "--help", "-v", "-V", "version", "/tmp/newrelic-infra.log", "/var/tmp/.oracle/npohasd*", "/dest/*",
    "/opt/Symantec/*", "/tmp/fzf*", "/var/tmp/portage/sys-apps/portage-*", "/tmp/elasticsearch*"
  ) or
  process.command_line like (
    "mkfifo*.json", "mkfifo*.txt", "mkfifo*.fifo", "mkfifo*/pipes/std*", "mkfifo*-m*600*/tmp/circleci.*/pipe",
    "/tmp/phpstderr"
  ) or
  process.parent.args in (
    "check-trigger.sh", "load-fas-final.sh", "load-kpi-history.sh", "load-fas-table.sh", "load-kpi-gsheet.sh",
    "/etc/bacula/scripts/mysql-dump.sh"
  ) or
  (process.parent.command_line == "/bin/bash -ue .command.run" and process.args : "/dev/shm/nxf.*/.command.*") or
  process.parent.command_line == "bash /usr/lib/portage/python3.12/estrip --dequeue" or
  (process.command_line == "mkfifo" and process.args_count == 1)
)
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "7.15.0"
