[rule]
description = """
Detects a suspicious child process of either the Kibana or Kibana Node process indicating a possible remote code
execution attempt.
"""
id = "0b206183-7f90-461d-80b3-8a147147ae78"
license = "Elastic License v2"
name = "Suspicious Kibana Child Process"
os_list = ["linux"]
version = "1.0.14"

query = '''
process where event.type == "start" and 
    process.parent.executable : ("*/kibana/node/bin/node", 
                                 "*/kibana/bin/kibana") and 
    process.name : ("bash", 
                    "sh", 
                    "awk", 
                    "sed", 
                    "curl", 
                    "python*", 
                    "openssl", 
                    "cat", 
                    "nc", 
                    "php", 
                    "perl", 
                    "whoami", 
                    "pwd"
                    ) and not
    process.command_line : ("/bin/sh -c lsb_release -a", "/bin/sh -c git rev-parse --short HEAD",
    "echo --unhandled-rejections=warn") and not
    process.executable : ("/var/lib/docker/*", "/run/containerd/*")
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1190"
name = "Exploit Public-Facing Application"
reference = "https://attack.mitre.org/techniques/T1190/"


[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "7.15.0"
